language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
env:
  DOCKER_COMPOSE_VERSION: 1.5.0
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - ./gradlew downloadDependencies
  - mkdir -p "$HOME/bin";
  - export PATH="$PATH:$HOME/bin";
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > "$HOME/bin/docker-compose";
  - chmod +x "$HOME/bin/docker-compose";
script:
  - sudo docker-compose up -d
  - ./gradlew check integrationTest
  - sudo docker-compose down
after_script:
  - ./gradlew sendCoverageToCodacy
